# Generated by Django 6.0.2 on 2026-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_stock'),
        ('wishlist', '0002_rename_product_name_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='variations',
            field=models.ManyToManyField(to='store.variation'),
        ),
    ]
