# Generated by Django 6.0.1 on 2026-01-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
