# Generated by Django 6.0 on 2026-01-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availabe',
            new_name='is_available',
        ),
    ]
