# Generated by Django 6.0 on 2026-02-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
