# Generated by Django 6.0 on 2026-02-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_email_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
